name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # This triggers the script every time you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 92.112.197.130
          username: u519226541
          # We will set this secret in the next step
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 65002
          script: |
            cd public_html
            git pull origin main